services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:5173"          # map host:container
    environment:
      VITE_API: "http://backend:4000"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      POSTGRES_URL: "postgres://postgres:postgres@db:5432/spinwheel"
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "spinwheel"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:

